version: '3.8'

services:
  # watcher: 
  #   build: "./server"
  #   working_dir: "/home/server"
  #   volumes:
  #     - "./server:/home/server"
  #   depends_on:
  #     - db
  #     - redis
  #   command: yarn watch
  server: 
    build: "./server"
    platform: linux/amd64
    working_dir: "/home/server"
    volumes:
      - "./server:/home/server"
    ports:
      - "3001:3001"
    hostname: server
    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION_STRING=postgresql://serene:password@127.0.0.1:5432
  # web: 
  #   build: "./web"
  #   working_dir: "/home/web"
  #   volumes:
  #     - "./web:/home/web"
  #   ports:
  #     - "3000:3000"
  #   hostname: web
  #   depends_on:
  #     - db
  #     - redis
  #     - server
  db: 
    container_name: 'serene'
    image: "postgres:14.1"
    volumes: 
      - "./tmp/db:/var/lib/postgresql/data"
    ports: 
      - "5432:5432"
    hostname: serene-db
    environment: 
      POSTGRES_USER: "serene"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "serene_development"
  redis: 
    image: redis:6.2-alpine
    container_name: sereneredis
    ports:
      - '6379:6379'
    volumes: 
      - "./tmp/cache:/data"